// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Models;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(WebContext))]
    partial class WebContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI.Models.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("WebAPI.Models.News", b =>
                {
                    b.Property<Guid>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("Click")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("EndDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("InsertDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("InsertEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Title")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("UpdateDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("UpdateEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NewsId");

                    b.HasIndex("InsertEmployeeId");

                    b.HasIndex("UpdateEmployeeId");

                    b.ToTable("News");
                });

            modelBuilder.Entity("WebAPI.Models.NewsFiles", b =>
                {
                    b.Property<Guid>("NewsFilesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Extension")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("NewsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NewsFilesId");

                    b.HasIndex("NewsId");

                    b.ToTable("NewsFiles");
                });

            modelBuilder.Entity("WebAPI.Models.News", b =>
                {
                    b.HasOne("WebAPI.Models.Employee", "InsertEmployee")
                        .WithMany("NewsInsertEmployees")
                        .HasForeignKey("InsertEmployeeId")
                        .IsRequired();

                    b.HasOne("WebAPI.Models.Employee", "UpdateEmployee")
                        .WithMany("NewsUpdateEmployees")
                        .HasForeignKey("UpdateEmployeeId")
                        .IsRequired();

                    b.Navigation("InsertEmployee");

                    b.Navigation("UpdateEmployee");
                });

            modelBuilder.Entity("WebAPI.Models.NewsFiles", b =>
                {
                    b.HasOne("WebAPI.Models.News", "News")
                        .WithMany("NewsFiles")
                        .HasForeignKey("NewsId")
                        .IsRequired();

                    b.Navigation("News");
                });

            modelBuilder.Entity("WebAPI.Models.Employee", b =>
                {
                    b.Navigation("NewsInsertEmployees");

                    b.Navigation("NewsUpdateEmployees");
                });

            modelBuilder.Entity("WebAPI.Models.News", b =>
                {
                    b.Navigation("NewsFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
